### ISSUE TITLE
ShippingEvaluationContext equivalent?

### ISSUE THREAD

**Issue by fcu423** [VirtoCommerce/vc-module-shipping#27]
I am trying to access the cart items from a ShippingMethod to calculate the shipping total.

The ShippingEvaluationContext used [here](https://github.com/VirtoCommerce/vc-module-fedex/blob/master/VirtoCommerce.FedExModule.Web/VirtoCommerce.FedExModule.Web/FedExShippingMethod.cs) doesn't exist in the net core version of Virto.

What would be the appropriate way to access the cart items in the newer version?

(Apologies in advance if this type of inquiries shouldn't be here).

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7902 has been created

**Comment by Vectorfield4** [comment]
Hi, @fcu423! Here is [ShippingRateEvaluationContext](https://github.com/VirtoCommerce/vc-module-shipping/blob/dev/src/VirtoCommerce.ShippingModule.Core/Model/ShippingRateEvaluationContext.cs). You need to create your own Shipping Method and override [Calculate Rates](https://github.com/VirtoCommerce/vc-module-shipping/blob/dev/src/VirtoCommerce.ShippingModule.Data/FixedRateShippingMethod.cs#L22) method. Then register your shipping method like [this](https://github.com/VirtoCommerce/vc-module-shipping/blob/dev/src/VirtoCommerce.ShippingModule.Web/Module.cs#L53).

**Comment by fcu423** [comment]
@Vectorfield4 Maybe I am missing something, but the context you mention only exposes the Currency property. There is no acces to the cart items or any context regarding the cart.

How can I access the cart (items) to calculate the rate of the shopping?

**Comment by Vectorfield4** [comment]
@fcu423 You can cast to ShippingEvaluationContext. Then override this [method ](https://github.com/VirtoCommerce/vc-module-shipping/blob/dev/src/VirtoCommerce.ShippingModule.Data/FixedRateShippingMethod.cs#L24) (look on line 24).

``` csharp
public class NewShippingMethod : ShippingMethod
{
    public FixedRateShippingMethod() : base("New")
    {
    }

    public override IEnumerable<ShippingRate> CalculateRates(IEvaluationContext context)
    {
        if (!(context is ShippingEvaluationContext shippingContext))
        {
            throw new ArgumentException(nameof(context));
        }

        var cart = shippingContext.ShoppingCart; 

        // Calculation code here

        return null; 
    }
}
```

**Comment by Vectorfield4** [comment]
@fcu423 By default IEvaluationContext is [ShippingEvaluationContext](https://github.com/VirtoCommerce/vc-module-cart/blob/dev/src/VirtoCommerce.CartModule.Core/Model/ShippingEvaluationContext.cs).

**Comment by fcu423** [comment]
@Vectorfield4 That all made sense and I got it working now.
